//CUSTOMERLOOKUP
ALTER TABLE TRUSTBANKDATA.PUBLIC.CUSTOMERLOOKUP
ADD CONSTRAINT pk_cardholderid PRIMARY KEY (CARDHOLDERID)
ADD CONSTRAINT fk_atmid FOREIGN KEY(ATMID) REFERENCES ATM_LOCATION_LOOKUP(LOCATIONID)
ADD CONSTRAINT fk_branchid FOREIGN KEY (BRANCH-ID) REFERENCES BRANCH_LOOKUP(BRANCH_ID)
ADD CONSTRAINT fk_cust_demo FOREIGN KEY (CARDHOLDERID-ID) REFERENCES CUSTOMERDEMOGRAPHICS(CARDHOLDERID);

// CUSTOMER DEMOGRPAHICS 
ALTER TABLE TRUSTBANKDATA.PUBLIC.CUSTOMERLOOKUP
ADD CONSTAINT pk_cardholderid PRIMARY KEY (CARDHOLDERID)
ADD CONSTRAINT fk_cust_lookup FOREIGN KEY (CARDHOLDERID) REFERENCES CUSTOMER_LOOKUP(CARDHOLDERID);

// BRANCH LOOKUP 
ALTER TABLE  TRUSTBANKDATA.PUBLIC.BRANCH_LOOKUP
ADD CONSTRAINT pk_branchid PRIMARY KEY (BRANCH_ID)
ADD CONSTRAINT 


