//CUSTOMERLOOKUP
ALTER TABLE TRUSTBANKDATA.PUBLIC.CUSTOMERLOOKUP
ADD CONSTRAINT pk_cardholderid PRIMARY KEY (CARDHOLDERID);
ALTER TABLE TRUSTBANKDATA.PUBLIC.CUSTOMERLOOKUP
ADD CONSTRAINT fk_atmid FOREIGN KEY (ATMID) 
REFERENCES ATM_LOCATION_LOOKUP(LOCATIONID);
ALTER TABLE TRUSTBANKDATA.PUBLIC.CUSTOMERLOOKUP
ADD CONSTRAINT fk_branchid FOREIGN KEY (BRANCH-ID) 
REFERENCES BRANCH_LOOKUP(BRANCH_ID);
ALTER TABLE TRUSTBANKDATA.PUBLIC.CUSTOMERLOOKUP
ADD CONSTRAINT fk_cust_demo FOREIGN KEY (CARDHOLDERID-ID) 
REFERENCES CUSTOMERDEMOGRAPHICS(CARDHOLDERID);

// CUSTOMER DEMOGRPAHICS 
ALTER TABLE TRUSTBANKDATA.PUBLIC.CUSTOMERLOOKUP
ADD CONSTAINT pk_cardholderid PRIMARY KEY (CARDHOLDERID);
ALTER TABLE TRUSTBANKDATA.PUBLIC.CUSTOMERLOOKUP
ADD CONSTRAINT fk_cust_lookup FOREIGN KEY (CARDHOLDERID) 
REFERENCES CUSTOMERLOOKUP(CARDHOLDERID);

// BRANCH LOOKUP 
ALTER TABLE TRUSTBANKDATA.PUBLIC.BRANCH_LOOKUP
ADD CONSTRAINT pk_branchid PRIMARY KEY (BRANCH_ID);

// BRANCH PERFORMANCE 
ALTER TABLE TRUSTBANKDATA.PUBLIC.BRANCH_PERFORMANCE 
ADD CONSTRAINT pk_branchid_date PRIMARY KEY (BRANCH_ID, DATE);
ALTER TABLE TRUSTBANKDATA.PUBLIC.BRANCH_PERFORMANCE 
ADD CONSTRAINT fk_branchlookupid FOREIGN KEY (BRANCHID)
REFERENCES BRANCH_LOOKUP (BRANCHID);

// BRANCH FINANCE 
ALTER TABLE TRUSTBANKDATA.PUBLIC.BRANCH_TABLE
ADD CONSTRAINT pk_branchid_date PRIMARY KEY (BRANCH_ID, DATE);
ALTER TABLE TRUSTBANKDATA.PUBLIC.BRANCH_TABLE 
ADD CONSTRAINT fk_branchlookupid FOREIGN KEY (BRANCHID)
REFERENCES BRANCH_LOOKUP (BRANCHID);

// INVESTMENTS 
ALTER TABLE TRUSTBANKDATA.PUBLIC.GENERATED_INVESTMENT_DATA 
ADD CONSTRAINT pk_cardholderid_investmentid PRIMARY KEY (CARDHOLDERID, INVESTMENTID);
ALTER TABLE TRUSTBANKDATA.PUBLIC.GENERATED_INVESTMENT_DATA 
ADD CONSTRAINT fk_cust_lookup FOREIGN KEY (CARDHOLDERID) 
REFERENCES CUSTOMERLOOKUP(CARDHOLDERID);

// LOANS 
ALTER TABLE TRUSTBANKDATA.PUBLIC.LOAN
ADD CONSTRAINT pk_cardholderid_loantid PRIMARY KEY (CARDHOLDERID, LOAN_ID);
ALTER TABLE TRUSTBANKDATA.LOAN
ADD CONSTRAINT fk_cust_lookup FOREIGN KEY (CARDHOLDERID) 
REFERENCES CUSTOMERLOOKUP(CARDHOLDERID);

// ATM LOCATIONS 
ALTER TABLE TRUSTBANKDATA.PUBLIC.ATM_LOCATION_LOOKUP
ADD CONSTRAINT pk_locationid PRIMARY KEY (LOCATION_ID);

// TRANSACTIONS 
ALTER TABLE TRUSTBANKDATA.PUBLIC.TRANSACTIONS
ADD CONSTRAINT pk_transactionid PRIMARY KEY (TRANSACTIONID);
ALTER TABLE TRUSTBANKDATA.PUBLIC.TRANSACTIONS
ADD CONSTRAINT fk_cust_lookup FOREIGN KEY (CARDHOLDERID) 
REFERENCES CUSTOMERLOOKUP(CARDHOLDERID);
ALTER TABLE TRUSTBANKDATA.PUBLIC.TRANSACTIONS
ADD CONSTRAINT fk_atmid FOREIGN KEY (ATMID) 
REFERENCES ATM_LOCATION_LOOKUP(LOCATIONID);

ALTER TABLE TRUSTBANKDATA.PUBLIC.TRANSACTIONS
ADD CONSTRAINT fk_trans_type FOREIGN KEY (TRANSACTIONTYPEID) 
REFERENCES TRANSACTION_LOOKUP(TRANSACTIONTYPEID);


//TRANSACTION LOOKUP 
ALTER TABLE TRUSTBANKDATA.PUBLIC.TRANSACTION_TYPE_LOOKUP
ADD CONSTRAINT pk_transaction_typeid PRIMARY KEY (TRANSACTIONTYPEID);


