// finding all tables in schema 
SELECT 'TRUSTBANK.raw.' || table_name AS full_table_name
FROM TRUSTBANK.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'RAW';

// table diagnostic features 
-- 1. TRUSTBANK.raw.FCT_TRANSACTIONS
SELECT * FROM TRUSTBANK.raw.FCT_TRANSACTIONS LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.FCT_TRANSACTIONS;

-- 2. TRUSTBANK.raw.LOANS
SELECT * FROM TRUSTBANK.raw.LOANS LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.LOANS;

-- 3. TRUSTBANK.raw.BRANCH_PERFORMANCE
SELECT * FROM TRUSTBANK.raw.BRANCH_PERFORMANCE LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.BRANCH_PERFORMANCE;

-- 4. TRUSTBANK.raw.BRANCH_FINANCE
SELECT * FROM TRUSTBANK.raw.BRANCH_FINANCE LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.BRANCH_FINANCE;

-- 5. TRUSTBANK.raw.CALENDAR_LOOKUP
SELECT * FROM TRUSTBANK.raw.CALENDAR_LOOKUP LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.CALENDAR_LOOKUP;

-- 6. TRUSTBANK.raw.CUSTOMER_BANKING_DETAILS
SELECT * FROM TRUSTBANK.raw.CUSTOMER_BANKING_DETAILS LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.CUSTOMER_BANKING_DETAILS;

-- 7. TRUSTBANK.raw.INVESTMENT_DATA
SELECT * FROM TRUSTBANK.raw.INVESTMENT_DATA LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.INVESTMENT_DATA;

-- 8. TRUSTBANK.raw.ATM_LOCATIONS
SELECT * FROM TRUSTBANK.raw.ATM_LOCATIONS LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.ATM_LOCATIONS;

-- 9. TRUSTBANK.raw.BRANCH_LOOKUP
SELECT * FROM TRUSTBANK.raw.BRANCH_LOOKUP LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.BRANCH_LOOKUP;

-- 10. TRUSTBANK.raw.TRANSACTION_LOOKUP
SELECT * FROM TRUSTBANK.raw.TRANSACTION_LOOKUP LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.TRANSACTION_LOOKUP;

-- 11. TRUSTBANK.raw.CUSTOMER_DEMOGRAPHICS
SELECT * FROM TRUSTBANK.raw.CUSTOMER_DEMOGRAPHICS LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.CUSTOMER_DEMOGRAPHICS;

-- 12. TRUSTBANK.raw.HOUR_LOOKUP
SELECT * FROM TRUSTBANK.raw.HOUR_LOOKUP LIMIT 5;

DESCRIBE TABLE TRUSTBANK.raw.HOUR_LOOKUP;
